app = "archie-redis"
primary_region = "ams"

[http_service]
  internal_port = 6379
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "redis_data"
  destination = "/data"
